title: "Performance improvement for function XYZ"
body: |
  ## Summary of changes
  
  In this pull request, I propose the following improvements:
  
  1. Reduction of function XYZ execution time by 20%.
  2. Improved stability of function XYZ.
  
  ## Tests
  
  I conducted the following tests:
  
  - Performance test (test #1)
  - Stability tests (tests #2-#5)
  
  All tests passed successfully.
  
  ## Relation to other pull requests
  
  This pull request is related to pull request #123, which concerns optimization of function ABC.
  
  ---
  
  ### Review request
  
  Please review this pull request and let me know if you have any comments or suggestions.
  
  Thank you for your attention!
