name: Pull Request Template
description: Стандартный шаблон для создания Pull Request
title: "[PR] Краткое описание изменений"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Описание изменений
        Пожалуйста, опишите, какие изменения вы внесли и почему.

  - type: textarea
    id: description
    attributes:
      label: "Описание изменений"
      description: "Подробно опишите, что было изменено и зачем."
    validations:
      required: true

  - type: textarea
    id: related-issues
    attributes:
      label: "Связанные задачи"
      description: "Укажите номера связанных issue (например, #123)."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "Проверочный список"
      description: "Пожалуйста, отметьте выполненные пункты."
      options:
        - label: "Я протестировал(а) свои изменения."
          required: true
        - label: "Я обновил(а) документацию, если это необходимо."
          required: true
        - label: "Мой код соответствует стандартам стиля."
          required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: "Дополнительные заметки"
      description: "Добавьте любую дополнительную информацию, которая может быть полезна."
    validations:
      required: false
